### ISSUE TITLE
rpy2 issues on Windows preventing installation

### ISSUE THREAD

**Issue by seugurlu** [mlverse/pysparklyr#125]
Hi.

I understand from version 0.1.4, install_pyspark() and install_databricks() functions are installing rpy2 as a part of the Python environment being set up. On Windows, this seems to cause an issue as there are problems with installing rpy2 on Windows. rpy2 documentation also states that rpy2 on Windows is currently not supported (e.g. see [rpy2 documentation](https://rpy2.github.io/doc/v3.5.x/html/overview.html#installation)).

Despite some online search coming up with suggestions on how rpy2 can be installed on Windows machines, I failed to achieve this on my end using a corporate laptop with limited rights. Considering users such as me, I was wondering if rpy2 installation can be made optional? I appreciate this will make some features of pysparklyr not available to users but the only solution we have been able to find so far is to use version 0.1.3, which is less ideal.

Thanks for your consideration.

**Comment by edgararuiz** [comment]
Thank you for the call out, I think we should be able add an enhancement that skips installing `rpy2` if on a Windows machine, and to also add a check when running `spark_apply()` and automatically attempt to install it. We do something similar for the huge TF libraries needed to run `ml_` functions, we don't install them until you try to run them for the first time

**Comment by edgararuiz** [comment]
@seugurlu - Can you try the dev version to make sure it solves your issue?

```
pak::pak("mlverse/pysparklyr@updates")
```

**Comment by paddytobias** [comment]
Thanks that worked for me too. Any idea when this update is going to be released?

**Comment by francisbarton** [comment]
Just to note that `main` branch is now up to date with the `updates` branch, so
```
pak::pak("mlverse/pysparklyr")
```

should work now (without the `@updates`) - if I understand correctly.
