### ISSUE TITLE
update `install_pyspark()` to `pysparklyr::install_pyspark()` in README.md

### ISSUE THREAD

**Issue by dskard** [mlverse/pysparklyr#14]
In setup instructions at https://github.com/mlverse/pysparklyr#setup, we load the library `sparklyr` and call the function `install_pyspark()`. The function `install_pyspark()` comes from the library `pysparklyr`, which we don't load in the instructions.

We should either load the library with `library(pysparklyr)` or convert our calls from `install_pyspark()` to `pysparklyr::install_pyspark()`

https://github.com/mlverse/pysparklyr/blob/b7188a086430f4a428bba68695df97ea241cc92e/README.Rmd#L56-L60

**Comment by edgararuiz** [comment]
Moved instructions to website: https://spark.rstudio.com/deployment/databricks-spark-connect.html#package-installation
