### ISSUE TITLE
sparklyr copy_to not working with unity catalog

### ISSUE THREAD

**Issue by romangehrn** [mlverse/pysparklyr#33]
Cannot copy dataframe to sparkdataframe.

`copy_to(sc, mtcars)`

The following error is displayed.
```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
pyspark.errors.exceptions.connect.AnalysisException: [UC_COMMAND_NOT_SUPPORTED.WITHOUT_RECOMMENDATION] The command(s): ResolvedIdentifier are not supported in Unity Catalog. ;
ResolvedIdentifier com.databricks.sql.managedcatalog.UnityCatalogV2Proxy@1fcdb3ef, default.mtcars
```

**Comment by edgararuiz** [comment]
Hi, would you mind sharing the output of `pysparklyr::installed_components()` in your environment?

**Comment by romangehrn** [comment]
> Hi, would you mind sharing the output of `pysparklyr::installed_components()` in your environment?

── R packages 
• `sparklyr` (1.8.3)
• `pysparklyr` (0.0.0.9004)

── Python executable 
/Users/ran/.virtualenvs/r-sparklyr/bin/python

── Python libraries 
• databricks-connect (13.3.1)
• pyspark (3.4.1)

**Comment by edgararuiz** [comment]
Is the name of the table you want actually "ch_lab.company.test", or are you attempting to save the data under the "company" schema, in the "ch_lab" catalog. If so, that's not really what `copy_to()` does, I believe that its unsupported for now. `copy_to()` is for data that will reside in the Spark session only

**Comment by romangehrn** [comment]
Exactly i want to write the table "test" to catalog "ch_lab", schema "company". But i get the error also without the, see first entry. Do we need to change some Settings in Databricks/Unity Catalog? That a simple `copy_to(sc, mtcars)` is working?

**Comment by edgararuiz** [comment]
Right, a simple `copy_to(sc, mtcars)` should be working, is that not the case in your environment?

**Comment by romangehrn** [comment]
Sadly not, reading is no problem ;) i also updated all packages today:

`── R packages 
• `sparklyr` (1.8.3)
• `pysparklyr` (0.0.0.9004)

── Python executable 
/Users/ran/.virtualenvs/r-sparklyr/bin/python

── Python libraries 
• databricks-connect (13.3.2)
• pyspark (3.4.1)`

Do you have also Unity Catalog in your Databricks environment?

**Comment by romangehrn** [comment]
With the currenty version it is now working :)

`sparklyr::spark_write_table(sparklyr::sdf_copy_to(sc, mtcars, overwrite = T), "ch_lab.construction_project.test", mode = "overwrite")`
