### ISSUE TITLE
import_check() does not recognise databricks connect

### ISSUE THREAD

**Issue by seugurlu** [mlverse/pysparklyr#36]
Hi,

As someone whose R workflow has been disrupted due to the update to databricks-connect, thank you very much for creating this great package. 

I have been trying to test it following the guidelines [here](https://spark.rstudio.com/deployment/databricks-spark-connect) and [here](https://www.databricks.com/blog/crossing-bridges-reporting-nyc-taxi-data-rstudio-and-databricks). I follow the guides and install the virtual environment in a standard way as the following and get the console message stating databricks-connect-14.0.0, among other packages, has been successfully installed.

```r
library(remotes)
install_github("sparklyr/sparklyr")
install_github("mlverse/pysparklyr")

pysparklyr::install_pyspark()
```

I then restart the environment and attemp to initiate a databricks connection (my connection parameters are in environmental variables correctly captured by the session) and get the error message below that states databricks connect could not be found in the r-sparklyr virtual environment.

```r
library(sparklyr)

sc <- spark_connect(method = "databricks_connect")
#! Python library 'databricks.connect' is not available in the 'r-sparklyr' virtual environment.
#  Install all of the needed python libraries using: pysparklyr::install_pyspark(virtualenv_name =
 # "r-sparklyr")
#---
#Backtrace:
#    ▆
 #1. └─sparklyr::spark_connect(method = "databricks_connect")
 #2.   ├─sparklyr::spark_connect_method(...)
 #3.   └─pysparklyr:::spark_connect_method.spark_method_databricks_connect(...)
 #4.     └─pysparklyr:::py_spark_connect(...)
 #5.       └─pysparklyr:::import_check("databricks.connect", virtualenv_name)
 #6.         └─cli::cli_abort(...)
 #7.           └─rlang::abort(...)
```

Checking the installed components returns the following (replacing the username part with [...]). I also tried manually uninstalling databricks-connect 14.0.0 and installing databricks-connect 13.3.* into the r-sparklyr virtual environment to make sure it is not a versioning issue but the problem above persisted.

```r
pysparklyr::installed_components()
#── R packages 
#• `sparklyr` (1.8.3)
#• `pysparklyr` (0.0.0.9004)

#── Python executable 
#[...]/Documents/.virtualenvs/r-sparklyr/Scripts/python.exe

#── Python libraries 
#• databricks-connect (14.0.0)
#• pyspark (3.4.1)
```

Reinstalling the environment by providing the virtualenv_name argument, as it is stated in the error message above and at this [link ](https://www.databricks.com/blog/crossing-bridges-reporting-nyc-taxi-data-rstudio-and-databricks) also did not resolve the issue--the function attempts to remove the environment but then returns the following error and I have to manually delete the folder and reinstall.

```r
pysparklyr::install_pyspark(virtualenv_name  = "r-sparklyr")
#Virtual environment "r-sparklyr" removed.
#Error in virtualenv_install(envname = envname, packages = packages, ignore_installed = pip_ignore_installed,  : 
# 'r-sparklyr' exists but is not a virtual environment
```

I would appreciate it if you can advise what the issue may be as the setup steps seem very straightforward but import_check() function seems to be unable to find the installed package despite identifying the correct virtual environment.

Best wishes,
Serhat

**Comment by edgararuiz** [comment]
Related to #25 

Will close and track on that Issue

**Comment by edgararuiz** [comment]
@seugurlu - Hi, what version of Python are you running?

**Comment by seugurlu** [comment]
Hi, It is 3.10.4.

**Comment by edgararuiz** [comment]
After getting the error from running `spark_connect()` again, can you run the following, and share the output here?

```
library(reticulate)
virtualenv_starter()
use_virtualenv("r-sparklyr")
import("databricks.connect")
py_version()
py_exe()
```

**Comment by seugurlu** [comment]
Sure, here are the outputs from each line:

```r
library(reticulate)
virtualenv_starter()
# "C:/Program Files/Python310/python.exe"
use_virtualenv("r-sparklyr")
import("databricks.connect")
#Error in py_module_import(module, convert = convert) : 
#  NameError: name 'base_events' is not defined
#Run `reticulate::py_last_error()` for details.
py_version()
# ‘3.10’
py_exe()
# "[...]/Documents/.virtualenvs/r-sparklyr/Scripts/python.exe" // [...] is my user folder.
```

**Comment by seugurlu** [comment]
Indeed, updating reticulate to the dev version resolved the issue. Thank you.

**Comment by edgararuiz** [comment]
Awesome, thanks for letting me know.
