### ISSUE TITLE
`Error: Unable to find conda binary. Is Anaconda installed?`

### ISSUE THREAD

**Issue by edgararuiz** [mlverse/pysparklyr#48]
Scenario:

```r
> library(sparklyr)
> sc <- spark_connect(cluster_id="xxxx", method = "databricks_connect")
! Retrieving version from cluster 'xxxx'
✔ Cluster version: '14.0'
Error: Unable to find conda binary. Is Anaconda installed?
```

This is an issue with `pysparklyr` in CRAN, there is a fix for it currently in the dev version (`0.1.9000` and above). Run the following to install:

```r
install.packages("pak")
pak::pak("mlverse/pysparklyr")
```

**Comment by edgararuiz** [comment]
Fixed in #46

**Comment by Mike-Hanna** [comment]
@edgararuiz I'd have appreciated a heads-up on the issue I reported in sparklyr [here] (https://github.com/sparklyr/sparklyr/issues/3384) instead of spending time trying to investigate what went wrong when the package when is got deployed to CRAN.

**Comment by edgararuiz** [comment]
Hi @Mike-Hanna , so sorry about that, I've been trying to cover blind spots as best as possible, which included opening this temporary Issues like this one here, and also included adding this issue on our site here: https://spark.rstudio.com/deployment/databricks-spark-connect.html#reported-problems. Bottom line, is that I haven't checked issued on `sparklyr` in a few days, so I missed it

**Comment by Mike-Hanna** [comment]
@edgararuiz No worries!

I tried version 0.1.9001 and now I'm getting this error.  Is this a known issue?

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  pyspark.errors.exceptions.connect.SparkConnectGrpcException: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found: spark.connect.SparkConnectService/ReattachExecute"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Method not found: spark.connect.SparkConnectService/ReattachExecute", grpc_status:12
```

**Comment by edgararuiz** [comment]
@Mike-Hanna - That is a new one to me.  Can you share with me the output of `pysparklyr::installed_components()` please?

**Comment by Mike-Hanna** [comment]
I had `databricks-connect (11.3.7)` for some reason, deleted the virtual environment and reinstalled it and everything looks good now.

I noticed this new behavior though, originally, it used to start the cluster if it's terminated and I don't get the connection until it's running. 

Now I get this error if the cluster was terminated at the time I run ```sparklyr::spark_connect```.  It starts the cluster though, but it doesn't wait until it's in a running state.

```
Error in `cluster_dbr_error()`:
! Spark connection error
• Possible cause = The cluster is initializing. Try again later
• status = StatusCode.FAILED_PRECONDITION
• details = "INVALID_STATE: Cluster xxx is in unexpected state Pending."
```

**Comment by edgararuiz** [comment]
Oh great! I'm glad that it the virtual environment works now

And yeah, unfortunately at that stage the connection already failed, so there's nothing else I can do. I thought to make `pysparklyr` retry the connection, like after a few seconds, but I felt like that kind of approach would be more intrusive than helpful

**Comment by Mike-Hanna** [comment]
@edgararuiz - correction...I got the same error again after the connection was established for a few minutes.

```
── R packages 
• `sparklyr` (1.8.3)
• `pysparklyr` (0.1.9001)

── Python executable 
~/.virtualenvs/r-sparklyr-databricks-13.3/bin/python

── Python libraries 
• databricks-connect (13.3.3)
• pyspark (3.5.0)
```

**Comment by edgararuiz** [comment]
Ok, that looks right. Can you do me a favor,  install the dev version of `reticulate` and try again?

**Comment by Mike-Hanna** [comment]
@edgararuiz What version? I updated to cran version `1.34.0`

**Comment by edgararuiz** [comment]
Does your RStudio Connections pane load like the first screenshot here? https://spark.rstudio.com/deployment/databricks-spark-connect.html#rstudios-connection-pane Or does it fail before it does that?

**Comment by Mike-Hanna** [comment]
I figured out the issue, I was installing other packages to the same virtual environment that I was using in the earlier script. One of those I was trying is pyspark which of course messes up the virtual environment. Remove it and it seems to be working fine except this error below when the cluster is in a terminated state.  It sometimes wait for the cluster though, so I'm not sure why is this happening.

Anyway, it's working now, I just need to start the cluster using the API before I call `spark_connect`.

Thank you!

```
Error in if (grepl("UNAVAILABLE", status_error)) { : 
  argument is of length zero
```

**Comment by edgararuiz** [comment]
New version now on CRAN: https://github.com/mlverse/pysparklyr/tree/v0.1.1
