### ISSUE TITLE
Add RStudio Connection Snippet extension for Databricks

### ISSUE THREAD

**Issue by sharon-wang** [mlverse/pysparklyr#53]
A "New Connection" entry for Databricks can be added to the RStudio IDE by following the [Connection Snippets extension docs](https://docs.posit.co/ide/user/ide/guide/data/connection-snippets.html).

Adding the Connection Snippet extension would create a new entry in the "New Connection" dialog in RStudio.

### Implementation Reference

I've manually set up a snippet in `/etc/rstudio/connections/Databricks.R`:

```R
library(sparklyr)
sc <- spark_connect(method = "databricks_connect", cluster_id = "${1: Cluster ID}")
```

This results in the following extensions to the Connections Wizard:

<img width="400" alt="image" src="https://github.com/mlverse/pysparklyr/assets/25834218/5a2650ac-c5c0-47e2-8e97-bb069c165bf3">

<img width="400" alt="image" src="https://github.com/mlverse/pysparklyr/assets/25834218/9f16bbff-a7e5-4a68-a3dc-44ceeafff324">

#### Existing Livy implementation in `sparklyr`:
- https://github.com/sparklyr/sparklyr/blob/main/inst/rstudio/connections.dcf
- https://github.com/sparklyr/sparklyr/blob/main/inst/rstudio/connections/Livy.R

**Comment by edgararuiz** [comment]
Being addressed in this branch: https://github.com/mlverse/pysparklyr/tree/snippet

**Comment by edgararuiz** [comment]
Fixed https://github.com/mlverse/pysparklyr/commit/0e1dde349c96be40b9d76b623a214285ea31a16d
