### ISSUE TITLE
Unset the `RETICULATE_PYTHON` variable if one is set

### ISSUE THREAD

**Issue by edgararuiz** [mlverse/pysparklyr#65]
Due to the complex Python version handling required to properly connect to a Spark/Databricks Connect instance, the default environment provided in `RETICULATE_PYTHON` will work. Maybe in very few cases it may work, but for the vast majority of cases  we will need a custom Python env.  If set, `reticulate` will prevent `sparklyr` from selecting a different environment.

The idea is to have the functions that serve as entry points, namely `spark_connect()`, and `install_databricks()`/ `install_pyspark()`, to unset `RETICULATE_PYTHON`  when they first run, so that they can create and interact with the correct Python environment.  As an escape-hatch,  this new behavior can be disabled via a new argument that we'll add to those entry point functions.

**Comment by nviets** [comment]
How do I trigger the escape-hatch behavior mentioned here to prevent `RETICULATE_PYTHON` from being unset?
